package com.rob729.newsfeed.ui.theme

import androidx.compose.ui.graphics.Color

val mdThemeLightPrimary = Color(0xFF00677F)
val mdThemeLightOnPrimary = Color(0xFFFFFFFF)
val mdThemeLightPrimaryContainer = Color(0xFFB6EBFF)
val mdThemeLightOnPrimaryContainer = Color(0xFF001F28)
val mdThemeLightSecondary = Color(0xFF4C626A)
val mdThemeLightOnSecondary = Color(0xFFFFFFFF)
val mdThemeLightSecondaryContainer = Color(0xFFCFE6F0)
val mdThemeLightOnSecondaryContainer = Color(0xFF071E26)
val mdThemeLightTertiary = Color(0xFF5A5C7E)
val mdThemeLightOnTertiary = Color(0xFFFFFFFF)
val mdThemeLightTertiaryContainer = Color(0xFFE0E0FF)
val mdThemeLightOnTertiaryContainer = Color(0xFF161937)
val mdThemeLightError = Color(0xFFBA1A1A)
val mdThemeLightErrorContainer = Color(0xFFFFDAD6)
val mdThemeLightOnError = Color(0xFFFFFFFF)
val mdThemeLightOnErrorContainer = Color(0xFF410002)
val mdThemeLightBackground = Color(0xFFFBFCFE)
val mdThemeLightOnBackground = Color(0xFF191C1D)
val mdThemeLightSurface = Color(0xFFFBFCFE)
val mdThemeLightOnSurface = Color(0xFF191C1D)
val mdThemeLightSurfaceVariant = Color(0xFF3C6472)
val mdThemeLightOnSurfaceVariant = Color(0xFF40484C)
val mdThemeLightOutline = Color(0xFF70787C)
val mdThemeLightInverseOnSurface = Color(0xFFEFF1F2)
val mdThemeLightInverseSurface = Color(0xFF2E3132)
val mdThemeLightInversePrimary = Color(0xFF5BD5FA)
val mdThemeLightShadow = Color(0xFF000000)
val mdThemeLightSurfaceTint = Color(0xFF00677F)
val mdThemeLightOutlineVariant = Color(0xFFBFC8CC)
val mdThemeLightScrim = Color(0xFF000000)

val mdThemeDarkPrimary = Color(0xFF5BD5FA)
val mdThemeDarkOnPrimary = Color(0xFF003543)
val mdThemeDarkPrimaryContainer = Color(0xFF004E60)
val mdThemeDarkOnPrimaryContainer = Color(0xFFB6EBFF)
val mdThemeDarkSecondary = Color(0xFFB3CAD4)
val mdThemeDarkOnSecondary = Color(0xFF1E333B)
val mdThemeDarkSecondaryContainer = Color(0xFF344A52)
val mdThemeDarkOnSecondaryContainer = Color(0xFFCFE6F0)
val mdThemeDarkTertiary = Color(0xFFC2C3EB)
val mdThemeDarkOnTertiary = Color(0xFF2B2E4D)
val mdThemeDarkTertiaryContainer = Color(0xFF424465)
val mdThemeDarkOnTertiaryContainer = Color(0xFFE0E0FF)
val mdThemeDarkError = Color(0xFFFFB4AB)
val mdThemeDarkErrorContainer = Color(0xFF93000A)
val mdThemeDarkOnError = Color(0xFF690005)
val mdThemeDarkOnErrorContainer = Color(0xFFFFDAD6)
val mdThemeDarkBackground = Color(0xFF191C1D)
val mdThemeDarkOnBackground = Color(0xFFE1E3E4)
val mdThemeDarkSurface = Color(0xFF191C1D)
val mdThemeDarkOnSurface = Color(0xFFE1E3E4)
val mdThemeDarkSurfaceVariant = Color(0xFF3C6472)
val mdThemeDarkOnSurfaceVariant = Color(0xFFBFC8CC)
val mdThemeDarkOutline = Color(0xFF8A9296)
val mdThemeDarkInverseOnSurface = Color(0xFF191C1D)
val mdThemeDarkInverseSurface = Color(0xFFE1E3E4)
val mdThemeDarkInversePrimary = Color(0xFF00677F)
val mdThemeDarkShadow = Color(0xFF000000)
val mdThemeDarkSurfaceTint = Color(0xFF5BD5FA)
val mdThemeDarkOutlineVariant = Color(0xFF40484C)
val mdThemeDarkScrim = Color(0xFF000000)

val seed = Color(0xFF3C6472)
