name: Build debug APK
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'assets/**'
      - '.github/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Create debug directory
        run: mkdir -p app/src/debug

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}
        run: |
          echo $GOOGLE_SERVICES > app/google-services.json
          echo $GOOGLE_SERVICES_DEBUG > app/src/debug/google-services.json

      - name: Build debug APK and run jvm tests
        env:
          NEWS_FEED_API_KEY: ${{ secrets.NEWS_FEED_API_KEY }}
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
