name: Run static code analysis using detekt
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'assets/**'
      - '.github/**/*.md'
jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Detekt
        env:
          NEWS_FEED_API_KEY: ${{ secrets.NEWS_FEED_API_KEY }}
        run: ./gradlew detekt
