name: Prod Release

on:
  workflow_dispatch:
    inputs:
      fastlane-input:
        description: "Fastlane input"
        required: false

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Write play store service account JSON and keystore secret content into file
        env:
          PLAY_STORE_SERVICE_ACCOUNT_CONFIG: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          KEYSTORE_FILE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          echo $PLAY_STORE_SERVICE_ACCOUNT_CONFIG > news-feed-play-config.json
          echo $KEYSTORE_PROPERTIES | base64 --decode > keystore.properties
          echo $KEYSTORE_FILE | base64 --decode > Keystore.p12

      - name: Create debug directory
        run: mkdir -p app/src/debug

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}
        run: |
          echo $GOOGLE_SERVICES > app/google-services.json
          echo $GOOGLE_SERVICES_DEBUG > app/src/debug/google-services.json    

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane lane for prod release
        run: fastlane android production
